### ISSUE TITLE
feat: SDK for using filter/lightpush

### ISSUE THREAD

**Issue by chair28980** [waku-org/js-waku#1507] opened 2023-08-24 21:13 UTC
Filter relies in many ways on the same building blocks as relay for its reliability, but in a modular, "pick your own tradeoffs" way:

- redundancy (for relay in full message connections, for filter in subscriptions)
- randomness (selecting random peers for connection/subscription, preferably with some peer cycling)
- periodically checking that you received all messages against a cache (this doesn't really exist yet for filter, but you could imagine using occasional store queries to achieve something similar)

As such it will be helpful to provide a configurable "reliability" SDK on top of filter for projects without the capacity to build these features from the ground up with filter.

Priority: not critical for launch

**Comment by fryorcraken** [comment] 2023-08-31 10:55
Where does this come from? Seems like a dupe of #1463

**Comment by chair28980** [comment] 2023-09-01 15:43
@fryorcraken  Looks like its a task under 2.1 here https://github.com/waku-org/research/issues/3 under the task breakdown comment.

**Comment by chair28980** [comment] 2023-09-01 19:32
@fryorcraken let me know if #1463 should replace this issue

**Comment by fryorcraken** [comment] 2023-09-08 01:23
superseded by  #1463

**Closed by fryorcraken** 2023-09-08 01:23 UTC
Labels: E:2023-1mil-users
