### ISSUE TITLE
lightPush.send returns Generic error

### ISSUE THREAD

**Issue by agazso** [waku-org/js-waku#1698] opened 2023-11-02 16:54 UTC
This is a **bug report**

## Problem

When calling `lightPush.send` and it fails sometimes it returns a `Generic error`, which contains no other information.

## Proposed Solutions

It would be better if the returned error would be more informative, so that you can tell what was the cause of the problem.

## Notes
- js-waku version: 0.0.20
- Environment (browser software and version, system software and version): Firefox and Chromium on Linux
- Nodes connected to too (e.g. Status test fleet): private nwaku node

![Screenshot from 2023-11-02 17-48-39](https://github.com/waku-org/js-waku/assets/230163/475bacac-24ec-4210-b227-031558e9f178)

**Comment by chair28980** [comment] 2024-01-04 15:56
Link issue with #1694

**Comment by chair28980** [comment] 2024-01-04 15:57
@agazso Issue will be picked up in #1694, closing this issue as duplicate. Please feel free to reopen if theres anything remaining that is not working as intended.

**Closed by chair28980** 2024-01-04 15:57 UTC
Labels: bug, enhancement, E:2.1: Production testing of existing protocols
